name: docker-build-push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.7'

    - name: Get version from file
      id: get_version
      run: |
        echo "version=$(cat version)" >> $GITHUB_ENV

    - name: Build for amd64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags="-w -s -X 'github.com/onlyLTY/dokcerCopilot/UGREEN/internal/config.Version=${{ env.version }}' -X 'github.com/onlyLTY/dokcerCopilot/internal/config.BuildDate=$(date)'" -o dist/linux/amd64/dokcerCopilot .

    - name: Build for arm64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -ldflags="-w -s -X 'github.com/onlyLTY/dokcerCopilot/UGREEN/internal/config.Version=${{ env.version }}' -X 'github.com/onlyLTY/dokcerCopilot/internal/config.BuildDate=$(date)'" -o dist/linux/arm64/dokcerCopilot .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/one-key-update:UGREEN
        push: true
