name: docker-build-push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'go-backend'

      - name: Checkout Frontend Repository
        uses: actions/checkout@v3
        with:
          repository: onlyLTY/dockerCopilotWeb
          path: 'react-frontend'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Build Frontend
        run: |
          cd react-frontend
          npm install
          npm run build

      - name: Copy Frontend Build to Go Project
        run: cp -R react-frontend/build/* go-backend/templates/

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'

      - name: Get version from file
        run: |
          echo "version=$(cat go-backend/version)" >> $GITHUB_ENV

      - name: Build for amd64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags="-w -s -X 'github.com/onlyLTY/dockerCopilot/UGREEN/internal/config.Version=${{ env.version }}' -X 'github.com/onlyLTY/dockerCopilot/UGREEN-DEV/internal/config.BuildDate=$(date)'" -o dist/linux/amd64/dockerCopilot .

      - name: Build for arm64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -ldflags="-w -s -X 'github.com/onlyLTY/dockerCopilot/UGREEN/internal/config.Version=${{ env.version }}' -X 'github.com/onlyLTY/dockerCopilot/UGREEN-DEV/internal/config.BuildDate=$(date)'" -o dist/linux/arm64/dockerCopilot .

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dockercopilot:UGREEN-DEV
          push: true
