name: UGREEN

on:
  workflow_dispatch:
  push:
    branches:
      - UGREEN
    paths:
      - version

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.7'

    - name: Get version from file
      id: get_version
      run: |
        echo "version=$(cat version)" >> $GITHUB_ENV

    - name: Build
      run: |
        CGO_ENABLED=0 GOARCH=${{ matrix.goarch }} go build -a -ldflags="-w -s -X 'github.com/onlyLTY/oneKeyUpdate/UGREEN/internal/config.Version=${{ env.version }}' -X 'github.com/onlyLTY/oneKeyUpdate/internal/config.BuildDate=$(date)'" -o onekeyupdate-${{ matrix.goarch }} .
        mv onekeyupdate-${{ matrix.goarch }} onekeyupdate-new
        tar -czvf onekeyupdate-new-${{ matrix.goarch }}.tar.gz onekeyupdate-new

    - name: List current directory
      run: ls -la

    outputs:
      version: ${{ steps.get_version.outputs.version }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Create GitHub Release
      run: |
        gh release create ${{ needs.build.outputs.version }} \
          artifacts/onekeyupdate-new-amd64.tar.gz \
          artifacts/onekeyupdate-new-arm64.tar.gz \
          --title "${{ needs.build.outputs.version }}" \
          --notes "Release of version ${{ needs.build.outputs.version }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
